base_images:
  base:
    name: "4.6"
    namespace: ocp
    tag: base
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.12
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.6"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-multi-arch-s390x-ipi
  cron: 0 0 * * 1
  steps:
    cluster_profile: libvirt-s390x
    pre:
    - ref: ipi-install-rbac
    workflow: multi-arch-e2e
- as: e2e-multi-arch-ppc64le-ipi
  cron: 0 0 * * 1
  steps:
    cluster_profile: libvirt-ppc64le
    pre:
    - ref: ipi-install-rbac
    workflow: multi-arch-e2e
zz_generated_metadata:
  branch: release-4.6
  org: openshift
  repo: multi-arch
