base_images:
  base:
    name: "4.6"
    namespace: ocp
    tag: base
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.6"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: e2e-multi-arch-ipi
  cron: 0 0 * * 1
  steps:
    cluster_profile: 
    pre:
    - ref: ipi-install-rbac
    workflow: multi-arch-e2e
zz_generated_metadata:
  branch: master
  org: openshift
  repo: release
  variant: ocp-4.6